[package]
name = "singing_bowl_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.2"
imgui = "0.11.0"
glow = "0.12.0"
glutin = "0.29.1"
winit = "0.29.3"
imgui-winit-support = "0.11.0"
imgui-glow-renderer = "0.11.0"
ringbuf = "0.3.3"
rustfft = "6.1.0"

[dev-dependencies]


